In [1]:
import numpy as np

In [2]:
A = np.array([2,4,6,8,10,12,14,16,18,20])
print(A)

[ 2  4  6  8 10 12 14 16 18 20]


In [3]:
B = np.zeros((3,3))
print(B)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
C = np.random.randint(1,101,5)
print(C)

[69 25 11 54 71]


In [5]:
D = np.linspace(0,5,10)
print(D)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
print("Shape:", A.shape)
print("Data type:", A.dtype)
print("Size:", A.size)
print("Dimensions:", A.ndim)


Shape: (10,)
Data type: int64
Size: 10
Dimensions: 1


In [7]:
print("Max value:", A.max())
print("Index of Max:", A.argmax())

print("Min value:", A.min())
print("Index of Min:", A.argmin())

Max value: 20
Index of Max: 9
Min value: 2
Index of Min: 0


In [8]:
E = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(E)

print("Element at row 1 column 2:", E[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1 column 2: 6


In [9]:
# assignment 2
import numpy as np

In [10]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])

print("arr1:\n", arr1)
print("arr2:\n", arr2)

arr1:
 [[1 2 3]
 [4 5 6]]
arr2:
 [10 20 30]


In [11]:
print("Addition:\n", arr1 + arr2)

Addition:
 [[11 22 33]
 [14 25 36]]


In [12]:
print("Subtraction:\n", arr1 - arr2)

Subtraction:
 [[ -9 -18 -27]
 [ -6 -15 -24]]


In [13]:
print("Multiplication:\n", arr1 * arr2)

Multiplication:
 [[ 10  40  90]
 [ 40 100 180]]


In [14]:
print("Division:\n", arr1 / arr2)

Division:
 [[0.1  0.1  0.1 ]
 [0.4  0.25 0.2 ]]


In [15]:
arr3 = np.array([1,4,9,16,25])

print("Square Root:", np.sqrt(arr3))
print("Exponential:", np.exp(arr3))
print("Sine:", np.sin(arr3))

Square Root: [1. 2. 3. 4. 5.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]


In [16]:
arr4 = np.array([[5,12,3],[8,2,7]])

print("Sum:", np.sum(arr4))
print("Max in columns:", np.max(arr4, axis=0))
print("Min in rows:", np.min(arr4, axis=1))

Sum: 37
Max in columns: [ 8 12  7]
Min in rows: [3 2]


In [17]:
arr1_float = arr1.astype(float)
print(arr1_float)

[[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
# assignment 3

In [19]:
import pandas as pd
import numpy as np

In [20]:
data = {
    'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank'],
    'Age': [25,30,np.nan,35,28,np.nan],
    'Score': [85,92,78,np.nan,88,95],
    'Grade': ['A','A','B','C','B','A']
}

In [21]:
df = pd.DataFrame(data)
print(df)

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B
3    Diana  35.0    NaN     C
4      Eve  28.0   88.0     B
5    Frank   NaN   95.0     A


In [23]:
print(df.head(3))     
print(df.shape)       
print(df.columns)     
print(df.dtypes)     

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B
(6, 4)
Index(['Name', 'Age', 'Score', 'Grade'], dtype='object')
Name      object
Age      float64
Score    float64
Grade     object
dtype: object


In [24]:
print(df.isnull())

    Name    Age  Score  Grade
0  False  False  False  False
1  False  False  False  False
2  False   True  False  False
3  False  False   True  False
4  False  False  False  False
5  False   True  False  False


In [25]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
print(df)

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie  29.5   78.0     B
3    Diana  35.0    NaN     C
4      Eve  28.0   88.0     B
5    Frank  29.5   95.0     A


In [26]:
df = df.dropna(subset=['Score'])
print(df)

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie  29.5   78.0     B
4      Eve  28.0   88.0     B
5    Frank  29.5   95.0     A
