In [6]:
import numpy as np
#convert list into array
arr=np.array([1,2,3])
print(arr)


#find the dimension of array
print(arr.ndim)

#type of array
print(type(arr))


[1 2 3]
1
<class 'numpy.ndarray'>


In [8]:
#numpy ones function
arr=np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [13]:
#make martix and only contain one block
arr=np.array([[4,8,2],[6,9,1],[3,7,5]])
print(arr)

#make martix using function
arr=np.ones((1,2))
print(arr)

[[4 8 2]
 [6 9 1]
 [3 7 5]]
[[1. 1.]]


In [17]:
#change the data type using ones function
arr2=np.ones((3,5),dtype=int)
print(arr2)


# int into the bool
arr2=np.ones((3,4),dtype=bool)
print(arr2)

#bool into string
arr2=np.ones((3,4),dtype=str)
print(arr2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [24]:
#numpy zero function
#same write but ones convert into the zeroo!
arr3=np.zeros((3,5))
print(arr3)

#find type
arr3=np.zeros((1,5))
print(type(arr3))

#change the type
arr3=np.zeros((3,5),dtype=str)
print(arr3)

arr3=np.zeros((3,4),dtype=bool)
print(arr3)

arr3=np.zeros((5,2),dtype=int)
print(arr3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]
[[False False False False]
 [False False False False]
 [False False False False]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
# create empty martix
emp=np.empty((3,4))
print(emp)

[[6.95266693e-310 9.27244089e-312 0.00000000e+000 9.27244089e-312]
 [4.47303294e-143 9.27244089e-312 2.23096177e+180 0.00000000e+000]
 [9.27244089e-312 9.27244089e-312 9.27244089e-312 0.00000000e+000]]


In [ ]:
#marke array sequence number using arg method
arr3=np.arange(1,13)
print(arr3)
#1st number is included and last number is excluded

#increament numbers
arr3=np.arange(0,13,2)
print(arr3)


#some equal numbers between two numbers
#smaj naii ayiii
arr3=np.linspace(1,10,20)
print(arr3)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  2  4  6  8 10 12]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [7]:
#SHAPING an Array
import numpy as np
arr=np.array([[3,4],[1,3],[5,4],[8,4]])
print(arr.size)
print(arr.ndim)
print(arr)
#reshape use when small dimension convert into big dimension
arr=arr.reshape(2,4)
print(arr)

8
2
[[3 4]
 [1 3]
 [5 4]
 [8 4]]
[[3 4 1 3]
 [5 4 8 4]]


In [ ]:
#covert array big dimension into small dimension
#work on single block of array
arr=np.array([[[1,2,3],[3,4,5],[5,6,7]]])

#using ravel function

s=arr.ravel()

print(s)

[1 2 3 3 4 5 5 6 7]


In [56]:
#using flatten
arr4=np.array([[[[1,4,6],[4,7,3],[2,6,9]]]])
print(arr4)
print(arr.size)
print(arr.ndim)

s=arr4.flatten()
s

[[[[1 4 6]
   [4 7 3]
   [2 6 9]]]]
9
3


array([1, 4, 6, 4, 7, 3, 2, 6, 9])

In [60]:
#convert row into column using transpose()
arr5=np.array([[[1,4,6],[4,7,3],[2,6,9]]])
print(arr5)
print(arr5.size)
print(arr5.ndim)
arr5.transpose()
arr5
#smaj naiii ayiii muhje

[[[1 4 6]
  [4 7 3]
  [2 6 9]]]
9
3


array([[[1, 4, 6],
        [4, 7, 3],
        [2, 6, 9]]])

In [16]:
#Do Math Functions using NUMPY

#To add two arrays use this function:
arr1=np.array([[1,8,5],[4,6,1]])
arr2=np.array([[1,2,5],[2,4,7]])
np.add(arr1,arr2)


#to sub numbers
#arr1=np.array([[1,8,5],[4,6,1]])
#arr2=np.array([[1,2,5],[2,4,7]])
#np.subtract(arr1,arr2)


#To multiply two arrays use this function:
#arr1=np.array([[1,8,5],[4,6,1]])
#arr2=np.array([[1,2,5],[2,4,7]])
#np.multiply(arr1,arr2)


#For DOT multiply of two arrays use this function:
#np.dot() me matrix multiplication hoti hai.condition
#(columns of first matrix) = (rows of second matrix)
arr1=np.array([[1,8,5],[4,6,1]])
arr2=np.array([[1,2,5],[2,4,7]])

result = np.dot(arr1, arr2.T)
print(result)


#divide two arrays use this function
#arr1=np.array([[1,8,5],[4,6,1]])
#arr2=np.array([[1,2,5],[2,4,7]])
#np.divide(arr1,arr2)


[[42 69]
 [21 39]]


In [15]:
#find maximum number n row
arr=np.array([1,3,2,5,4,9])
print(arr.max(axis=0))

#find maximum number in colomn i
arr=np.array([[3,6,5],[7,4,1],[6,9,3]])
print(arr.max(axis=1))

#find minimum number in row
arr=np.array([[1,4,6],[8,4,0],[1,6,2]])
print(arr.min(axis=0))

#find minimum number in column
# agr axis use karna hi to 2d banii pere gii
arr=np.array([[1,3,4,8,34,99,12,90]])
print(arr.min(axis=1))

9
[6 7 9]
[1 4 0]
[1]


In [ ]:
#find that index at which maximum number
arr=np.array([[1,4,6],[8,4,0],[1,6,2]])
print(arr.max(axis=0))
print(np.argmax(arr))

#find that index at which minimum number
arr=np.array([[1,4,6],[8,4,0],[1,6,2]])
print(arr.min(axis=1))
print(np.argmin(arr))

#find square root of an array
arr=np.array([1,4,6,5,7,2,9,1])#smaj naii ayiii
print(np.sqrt(arr))

[8 6 6]
3
[1 0 1]
5
[1.         2.         2.44948974 2.23606798 2.64575131 1.41421356
 3.         1.        ]


In [56]:
# task
arr=np.array([[[1,3,5],[1,3,6],[7,6,4]]])
print(arr.ndim)
print(arr)
#index ki smaj naii ayii
print(np.where==4)

arr=np.array([1,4,2,6,8,3])
print(arr)
print(arr.size)
arr.ndim
#convert 1d into 2d
print(arr.reshape(2,3))
#1d convert in 3d
arr.reshape(1,2,3)
#3d convert into 1d
arr=np.array([[[1,2,3],[4,5,6],[6,7,8]]])
print(arr.size)
arr.ndim
arr.flatten()

#2d me element acces karna
arr=np.array([[1,3,2,4],[1,3,7,8],[4,6,2,3]])
print(arr.ndim)
print(arr[1,3])
print(arr[2,3])
#2D ke kissi aik element ko replace krna
arr=np.array([[1,3,2,4],[1,3,7,8],[4,6,2,3]])
arr[2,3]=15
print(arr)

#slicing in 2d array
arr=np.array([[1,3,2,4],[1,3,7,8],[4,6,2,3]])
print(arr.ndim)
print(arr[0:3])
print(arr[:,1])


3
[[[1 3 5]
  [1 3 6]
  [7 6 4]]]
False
[1 4 2 6 8 3]
6
[[1 4 2]
 [6 8 3]]
9
2
8
3
[[ 1  3  2  4]
 [ 1  3  7  8]
 [ 4  6  2 15]]
2
[[1 3 2 4]
 [1 3 7 8]
 [4 6 2 3]]
[3 3 6]
